# Generated by Django 4.2.6 on 2023-10-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_band'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='descritpion',
            new_name='description',
        ),
    ]
